spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zoo
    username: root
    password: larysa
  jpa:
    hibernate:
      ddl-auto: create


spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

---
spring:
  profiles: production
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zoo
    username: root
    password: larysa
  jpa:
    hibernate:
      ddl-auto: create

spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect